version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        expose:
            - 5672
            - 15672
        ports:
            - 15672:15672
        hostname: rabbitmq
        networks:
            - rabbitmq
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    web:
        build:
            context: ./src
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - 2701:443
        volumes:
            - ./src/files:/var/www/html/files
            - ./src/database:/var/www/html/database
            - ./src/uploads:/var/www/html/uploads
            - ./src/scripts/metrics:/var/www/html/scripts/metrics
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - rabbitmq
            - python_server
        networks:
            - rabbitmq
    python_server:
        build:
            context: ./src
            dockerfile: Dockerfile_python
        restart: on-failure
        volumes:
            - ./src/logs:/usr/src/app/logs
            - ./src/files:/usr/src/app/files
            - ./src/database:/usr/src/app/database
            - ./src/uploads:/usr/src/app/uploads
            - ./src/scripts/metrics:/usr/src/app/scripts/metrics
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - rabbitmq
        networks:
            - rabbitmq

networks:
    rabbitmq:
        driver: bridge
